<#
.SYNOPSIS
Read-only Azure Virtual Desktop SSO cloud-side diagnostic.
.DESCRIPTION
Inspects AVD host pool RDP properties, session hosts, VM join hints, VM agent extensions,
Microsoft Entra RDP authentication, consent suppression, and Conditional Access signals where
permissions/modules are available. Produces console, JSON, and optional Markdown reports.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $ResourceGroupName,
    [Parameter(Mandatory)] [string] $HostPoolName,
    [string] $SubscriptionId,
    [string] $OutputPath = (Join-Path (Get-Location) ("avd-sso-cloud-{0}.json" -f (Get-Date -Format 'yyyyMMdd-HHmmss'))),
    [switch] $Markdown,
    [switch] $IncludeEntraChecks,
    [switch] $VerboseIdentity
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
function New-Finding { param([string]$Id,[ValidateSet('Info','Low','Medium','High','Critical')]$Severity,[string]$Title,[string]$Evidence,[string]$Impact,[string]$Recommendation,[string]$Domain='Unknown') [pscustomobject]@{ Id=$Id; Severity=$Severity; Title=$Title; Domain=$Domain; Evidence=$Evidence; Impact=$Impact; Recommendation=$Recommendation } }
function Add-Finding { param([object]$Finding) $script:Findings.Add($Finding) | Out-Null }
function Test-Command { param([string]$Name) [bool](Get-Command $Name -ErrorAction SilentlyContinue) }
function Mask-Identity { param([string]$Value) if ($VerboseIdentity -or [string]::IsNullOrWhiteSpace($Value)) { return $Value }; if ($Value -match '^(.).+(@.+)$') { return "$($Matches[1])***$($Matches[2])" }; return (($Value -replace '(?<=.{2}).','*')) }
function Redact-Text { param([AllowNull()][string]$Text) if ($null -eq $Text) { return $null }; $r=$Text -replace '(?i)(access_token|refresh_token|id_token|client_secret|password|secret|key)\s*[:=]\s*[^;\s,}\]]+', '$1=<redacted>'; $r -replace '(?i)Bearer\s+[A-Za-z0-9._\-]+', 'Bearer <redacted>' }
function Convert-RdpProperties { param([AllowNull()][string]$CustomRdpProperty) $map=[ordered]@{}; if([string]::IsNullOrWhiteSpace($CustomRdpProperty)){return $map}; foreach($line in ($CustomRdpProperty -split '[;\r\n]')){ $trim=$line.Trim(); if($trim -match '^([^:]+):([is]):(.*)$'){ $map[$Matches[1].ToLowerInvariant()]=$Matches[3].Trim() } }; $map }
function Get-PropValue { param([object]$Object,[string[]]$Names) foreach($n in $Names){ if($null -ne $Object -and $Object.PSObject.Properties.Name -contains $n){ return $Object.$n } }; return $null }
function Get-AvdHostPool { if(Test-Command Get-AzWvdHostPool){ return Get-AzWvdHostPool -ResourceGroupName $ResourceGroupName -Name $HostPoolName }; if(Test-Command Get-AzResource){ return Get-AzResource -ResourceGroupName $ResourceGroupName -ResourceType 'Microsoft.DesktopVirtualization/hostPools' -Name $HostPoolName -ExpandProperties }; throw 'Az.DesktopVirtualization or Az.Resources is required.' }
$script:Findings=[System.Collections.Generic.List[object]]::new()
$evidence=[ordered]@{ Script='Test-AvdSsoCloud'; Timestamp=(Get-Date).ToString('o'); ResourceGroupName=$ResourceGroupName; HostPoolName=$HostPoolName; SubscriptionId=$SubscriptionId; Checks=[ordered]@{} }
try {
    if(-not (Test-Command Get-AzContext)){ throw 'Az.Accounts is required. Run Install-Module Az.Accounts, then Connect-AzAccount.' }
    $ctx=Get-AzContext; if(-not $ctx){ throw 'No Azure context found. Run Connect-AzAccount first.' }
    if($SubscriptionId){ Set-AzContext -SubscriptionId $SubscriptionId | Out-Null; $ctx=Get-AzContext }
    $evidence.SubscriptionId=$ctx.Subscription.Id; $evidence.TenantId=$ctx.Tenant.Id; $evidence.Account=Mask-Identity ([string]$ctx.Account.Id)
    $hostPool=Get-AvdHostPool; $hpProps=if($hostPool.PSObject.Properties.Name -contains 'Properties'){$hostPool.Properties}else{$hostPool}
    $customRdp=[string](Get-PropValue $hpProps @('CustomRdpProperty','customRdpProperty')); $rdp=Convert-RdpProperties $customRdp
    $evidence.Checks.HostPool=[ordered]@{ Name=$HostPoolName; ResourceGroup=$ResourceGroupName; HostPoolType=(Get-PropValue $hpProps @('HostPoolType','hostPoolType')); PreferredAppGroupType=(Get-PropValue $hpProps @('PreferredAppGroupType','preferredAppGroupType')); ValidationEnvironment=(Get-PropValue $hpProps @('ValidationEnvironment','validationEnvironment')); CustomRdpProperty=(Redact-Text $customRdp); ParsedRdpProperties=$rdp }
    $entraRdp=$rdp['enablerdsaadauth']; $legacyAad=$rdp['targetisaadjoined']; $credSsp=$rdp['enablecredsspsupport']
    if($entraRdp -eq '1'){ Add-Finding (New-Finding 'RDP-ENTRA-AUTH-OK' 'Info' 'Host pool enables Microsoft Entra RDP authentication' 'enablerdsaadauth:i:1 is present.' 'Expected for modern AVD SSO.' 'No change required.' 'AVD host pool RDP properties') } else { Add-Finding (New-Finding 'RDP-ENTRA-AUTH-MISSING' 'High' 'Host pool is not configured for modern Entra RDP authentication' 'enablerdsaadauth:i:1 was not found in customRdpProperty.' 'Users can be prompted for credentials or fail Windows sign-in.' 'Add enablerdsaadauth:i:1 to the host pool RDP properties after review.' 'AVD host pool RDP properties') }
    if($legacyAad -eq '1' -and $entraRdp -ne '1'){ Add-Finding (New-Finding 'RDP-LEGACY-ONLY' 'Medium' 'Host pool uses legacy targetisaadjoined without modern enablerdsaadauth' 'targetisaadjoined:i:1 is present, enablerdsaadauth:i:1 is absent.' 'Legacy flags can be confusing and may not provide expected current SSO behavior.' 'Prefer enablerdsaadauth:i:1 for current AVD SSO configurations.' 'AVD host pool RDP properties') } elseif($legacyAad -eq '1' -and $entraRdp -eq '1'){ Add-Finding (New-Finding 'RDP-LEGACY-PRESENT' 'Low' 'Legacy targetisaadjoined is present alongside modern SSO flag' 'Both targetisaadjoined:i:1 and enablerdsaadauth:i:1 are present.' 'Usually not primary fault, but can confuse operators.' 'Document why targetisaadjoined is retained or remove it during a controlled change.' 'AVD host pool RDP properties') }
    if($credSsp -eq '0'){ Add-Finding (New-Finding 'RDP-CREDSSP-DISABLED' 'Medium' 'CredSSP support is disabled in RDP properties' 'enablecredsspsupport:i:0 is present.' 'Can alter credential flow and cause unexpected prompts.' 'Validate this setting is intentional.' 'AVD host pool RDP properties') }
    $sessionHosts=@(); if(Test-Command Get-AzWvdSessionHost){ $sessionHosts=@(Get-AzWvdSessionHost -ResourceGroupName $ResourceGroupName -HostPoolName $HostPoolName) }
    $evidence.Checks.SessionHosts=@($sessionHosts | ForEach-Object { [ordered]@{ Name=$_.Name; Status=(Get-PropValue $_ @('Status','status')); AllowNewSession=(Get-PropValue $_ @('AllowNewSession','allowNewSession')); UpdateState=(Get-PropValue $_ @('UpdateState','updateState')); LastHeartBeat=(Get-PropValue $_ @('LastHeartBeat','lastHeartBeat')) } })
    if($sessionHosts.Count -eq 0){ Add-Finding (New-Finding 'HOSTS-NONE-OR-NO-PERM' 'Medium' 'No session hosts returned' 'The script could not enumerate session hosts.' 'Could be empty host pool or missing Desktop Virtualization Reader permissions.' 'Confirm host pool has hosts and caller has read access.' 'Session host VM state') }
    foreach($sh in $sessionHosts){ $status=[string](Get-PropValue $sh @('Status','status')); if($status -and $status -notmatch 'Available'){ Add-Finding (New-Finding 'HOST-UNAVAILABLE' 'High' "Session host not available: $($sh.Name)" "Status=$status" 'SSO cannot be validated on an unavailable/unregistered host.' 'Repair AVD agent/registration before SSO-specific troubleshooting.' 'Session host VM state') } }
    if(Test-Command Get-AzVM){ $vmChecks=@(); foreach($sh in $sessionHosts){ $hostName=((($sh.Name -split '/')[-1]) -split '\.')[0]; $vm=Get-AzVM -ResourceGroupName $ResourceGroupName -Name $hostName -Status -ErrorAction SilentlyContinue; if($vm){ $extensions=@(Get-AzVMExtension -ResourceGroupName $ResourceGroupName -VMName $hostName -ErrorAction SilentlyContinue); $hasAadLogin=[bool]($extensions | Where-Object { $_.Name -match 'AADLoginForWindows|AzureADLoginForWindows' -or $_.Publisher -match 'AADLoginForWindows' }); $vmChecks += [ordered]@{ VmName=$hostName; PowerState=(@($vm.Statuses | Where-Object Code -like 'PowerState/*').DisplayStatus -join ','); Extensions=@($extensions | Select-Object Name,Publisher,ProvisioningState); HasAadLoginForWindowsExtension=$hasAadLogin }; if($entraRdp -eq '1' -and -not $hasAadLogin){ Add-Finding (New-Finding 'VM-AADLOGIN-EXT-MISSING' 'Medium' "AADLoginForWindows extension not detected on $hostName" 'VM extension inventory does not show AADLoginForWindows.' 'Entra-only sign-in may fail if the VM is intended to be Entra joined.' 'Confirm join model. Entra-joined hosts typically need the AADLoginForWindows extension.' 'Identity and join state') } } }; $evidence.Checks.VirtualMachines=$vmChecks }
    if($IncludeEntraChecks){ $entra=[ordered]@{ GraphAvailable=$false; Checks=@() }; if(Test-Command Connect-MgGraph){ $entra.GraphAvailable=$true; try { if(-not (Get-MgContext)){ Connect-MgGraph -Scopes 'Application.Read.All','Policy.Read.All','Directory.Read.All' -NoWelcome | Out-Null }; if(Test-Command Get-MgBetaServicePrincipalRemoteDesktopSecurityConfiguration){ $entra.RdpSecurityConfigurationNote='Graph beta remoteDesktopSecurityConfiguration command is available; inspect service principals if permissions allow.' } else { Add-Finding (New-Finding 'ENTRA-RDP-AUTH-NOT-VERIFIED' 'Medium' 'Could not verify tenant-level Entra RDP authentication setting' 'Microsoft Graph beta remoteDesktopSecurityConfiguration command is not available in this shell.' 'The host pool may be correct while the tenant is not enabled to issue RDP access tokens.' 'Install/update Microsoft.Graph Beta modules or verify isRemoteDesktopProtocolEnabled manually.' 'Identity and join state') }; if(Test-Command Get-MgIdentityConditionalAccessPolicy){ $policies=@(Get-MgIdentityConditionalAccessPolicy -All -ErrorAction SilentlyContinue | Where-Object { $_.State -ne 'disabled' }); $entra.ConditionalAccessPolicyCount=$policies.Count; if($policies.Count -gt 0){ Add-Finding (New-Finding 'CA-POLICIES-PRESENT' 'Low' 'Active Conditional Access policies exist' "$($policies.Count) active/enabled CA policies returned." 'CA can interrupt SSO with MFA, device, sign-in risk, or app controls.' 'Review CA sign-in logs for the affected user and AVD/Windows sign-in apps.' 'Policy and management plane') } } } catch { Add-Finding (New-Finding 'ENTRA-CHECKS-PARTIAL' 'Medium' 'Entra checks were partially completed' (Redact-Text $_.Exception.Message) 'Directory permissions or module gaps can hide SSO prerequisites.' 'Run with Graph read permissions or verify Entra prerequisites manually.' 'Identity and join state') } } else { Add-Finding (New-Finding 'GRAPH-NOT-INSTALLED' 'Low' 'Microsoft Graph PowerShell not installed' 'Connect-MgGraph command not found.' 'Cloud script cannot validate tenant-level RDP auth, consent, or CA.' 'Install Microsoft.Graph modules or run without Entra checks.' 'Identity and join state') }; $evidence.Checks.Entra=$entra }
} catch { Add-Finding (New-Finding 'SCRIPT-ERROR' 'Critical' 'Cloud diagnostic failed before completion' (Redact-Text $_.Exception.Message) 'The report may be incomplete.' 'Resolve the error and rerun.' 'Script runtime') }
$severityRank=@{ Critical=5; High=4; Medium=3; Low=2; Info=1 }; $actionable=@($Findings | Where-Object Severity -ne 'Info' | Sort-Object { -$severityRank[$_.Severity] })
$overall=if($actionable | Where-Object Severity -in @('Critical','High')){'Likely Misconfigured'}elseif($actionable | Where-Object Severity -eq 'Medium'){'Partially Configured'}elseif($actionable.Count -gt 0){'Needs Manual Review'}else{'Healthy'}
$top=if($actionable.Count){$actionable[0].Title}else{'No blocking cloud-side SSO issue detected by this script.'}
$report=[ordered]@{ OverallStatus=$overall; DetectedScenario='Cloud-side only; run Test-AvdSsoSessionHost.ps1 on a session host to classify join state'; TopLikelyCause=$top; Findings=@($Findings); Evidence=$evidence }
$report | ConvertTo-Json -Depth 12 | Set-Content -Path $OutputPath -Encoding UTF8
Write-Host "AVD SSO Cloud Diagnostic: $overall" -ForegroundColor Cyan; Write-Host "Top likely cause: $top"; Write-Host "Report: $OutputPath"; $Findings | Sort-Object { -$severityRank[$_.Severity] } | Format-Table Severity,Title,Domain -AutoSize
if($Markdown){ $mdPath=[IO.Path]::ChangeExtension($OutputPath,'.md'); $md=@('# AVD SSO Cloud Diagnostic','',"- Overall status: **$overall**","- Top likely cause: $top",'','## Findings'); foreach($f in ($Findings | Sort-Object { -$severityRank[$_.Severity] })){ $md += "### [$($f.Severity)] $($f.Title)`n- Domain: $($f.Domain)`n- Evidence: $($f.Evidence)`n- Impact: $($f.Impact)`n- Recommendation: $($f.Recommendation)`n" }; $md | Set-Content -Path $mdPath -Encoding UTF8; Write-Host "Markdown: $mdPath" }
