<#
.SYNOPSIS
Read-only Azure Virtual Desktop SSO session-host diagnostic.
.DESCRIPTION
Runs locally on a Windows AVD session host. Inspects dsregcmd, domain membership,
AVD agent services, relevant event logs, policy/registry hints, and endpoint reachability.
#>
[CmdletBinding()]
param(
    [string] $OutputPath = (Join-Path (Get-Location) ("avd-sso-sessionhost-{0}.json" -f (Get-Date -Format 'yyyyMMdd-HHmmss'))),
    [switch] $Markdown,
    [switch] $VerboseIdentity,
    [string[]] $AdditionalDomainControllers = @()
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'
function New-Finding { param([string]$Id,[ValidateSet('Info','Low','Medium','High','Critical')]$Severity,[string]$Title,[string]$Evidence,[string]$Impact,[string]$Recommendation,[string]$Domain='Unknown') [pscustomobject]@{ Id=$Id; Severity=$Severity; Title=$Title; Domain=$Domain; Evidence=$Evidence; Impact=$Impact; Recommendation=$Recommendation } }
function Add-Finding { param([object]$Finding) $script:Findings.Add($Finding) | Out-Null }
function Mask-Identity { param([string]$Value) if ($VerboseIdentity -or [string]::IsNullOrWhiteSpace($Value)) { return $Value }; if ($Value -match '^(.).+(@.+)$') { return "$($Matches[1])***$($Matches[2])" }; return (($Value -replace '(?<=.{2}).','*')) }
function Redact-Text { param([AllowNull()][string]$Text) if ($null -eq $Text) { return $null }; (($Text -replace '(?i)(access_token|refresh_token|id_token|client_secret|password|secret|key)\s*[:=]\s*[^;\s,}\]]+', '$1=<redacted>') -replace '(?i)Bearer\s+[A-Za-z0-9._\-]+', 'Bearer <redacted>') }
function Parse-DsReg { param([string[]]$Lines) $o=[ordered]@{}; foreach($line in $Lines){ if($line -match '^\s*([^:]+?)\s*:\s*(.*?)\s*$'){ $o[$Matches[1].Trim()]=$Matches[2].Trim() } }; $o }
function Get-RegValueSafe { param([string]$Path,[string]$Name) try { (Get-ItemProperty -Path $Path -Name $Name -ErrorAction Stop).$Name } catch { $null } }
function Get-RecentEventsSafe { param([string]$LogName,[int]$Max=20) try { Get-WinEvent -LogName $LogName -MaxEvents $Max -ErrorAction Stop | Select-Object TimeCreated,Id,ProviderName,LevelDisplayName,@{n='Message';e={ $m=Redact-Text ($_.Message -replace '\s+',' '); $m.Substring(0,[Math]::Min(500,$m.Length)) }} } catch { @() } }
function Test-Tcp { param([string]$Host,[int]$Port) try { $r=Test-NetConnection -ComputerName $Host -Port $Port -InformationLevel Quiet -WarningAction SilentlyContinue; [pscustomobject]@{Host=$Host;Port=$Port;Reachable=[bool]$r} } catch { [pscustomobject]@{Host=$Host;Port=$Port;Reachable=$false; Error=$_.Exception.Message} } }
$script:Findings=[System.Collections.Generic.List[object]]::new(); $scenario='Unknown / inconsistent join state'
$evidence=[ordered]@{ Script='Test-AvdSsoSessionHost'; Timestamp=(Get-Date).ToString('o'); ComputerName=$env:COMPUTERNAME; Checks=[ordered]@{} }
try {
    $identity=[Security.Principal.WindowsIdentity]::GetCurrent(); $evidence.Checks.CurrentIdentity=[ordered]@{ Name=(Mask-Identity $identity.Name); AuthenticationType=$identity.AuthenticationType; IsSystem=$identity.IsSystem }
    $dsregLines=@(); try { $dsregLines=& dsregcmd.exe /status 2>&1 } catch { Add-Finding (New-Finding 'DSREGCMD-FAILED' 'High' 'dsregcmd /status failed' (Redact-Text $_.Exception.Message) 'Cannot classify Entra/hybrid join state.' 'Run from an elevated PowerShell session on Windows.' 'Identity and join state') }
    $ds=Parse-DsReg $dsregLines; $evidence.Checks.DsRegCmd=$ds
    $azureAdJoined=$ds['AzureAdJoined']; $domainJoined=$ds['DomainJoined']; $enterpriseJoined=$ds['EnterpriseJoined']; $workplaceJoined=$ds['WorkplaceJoined']; $tenantName=$ds['TenantName']; $domainName=$ds['DomainName']
    $cs=Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue; $partOfDomain=if($cs){[bool]$cs.PartOfDomain}else{$null}; $evidence.Checks.ComputerSystem=[ordered]@{ PartOfDomain=$partOfDomain; Domain=$cs.Domain; Workgroup=$cs.Workgroup; Manufacturer=$cs.Manufacturer; Model=$cs.Model }
    if($azureAdJoined -eq 'YES' -and ($domainJoined -ne 'YES') -and -not $partOfDomain){$scenario='Entra-only session host'} elseif($azureAdJoined -eq 'YES' -and (($domainJoined -eq 'YES') -or $partOfDomain)){$scenario='Hybrid joined session host'} elseif($azureAdJoined -ne 'YES' -and (($domainJoined -eq 'YES') -or $partOfDomain)){$scenario='AD DS joined session host'}
    switch($scenario){
        'Entra-only session host' { Add-Finding (New-Finding 'JOIN-ENTRA-ONLY' 'Info' 'Session host appears Microsoft Entra joined only' "AzureAdJoined=$azureAdJoined; DomainJoined=$domainJoined; Tenant=$tenantName" 'Expected for Entra-native AVD SSO.' 'Verify host pool has enablerdsaadauth:i:1 and VM has AADLoginForWindows extension.' 'Identity and join state') }
        'Hybrid joined session host' { Add-Finding (New-Finding 'JOIN-HYBRID' 'Info' 'Session host appears hybrid joined' "AzureAdJoined=$azureAdJoined; DomainJoined=$domainJoined; Domain=$domainName" 'Hybrid SSO often depends on AD/Kerberos and identity consistency.' 'Verify Kerberos/Cloud Kerberos prerequisites and UPN/SID alignment.' 'Identity and join state') }
        'AD DS joined session host' { Add-Finding (New-Finding 'JOIN-AD-ONLY' 'High' 'Session host appears AD DS joined but not Entra joined' "AzureAdJoined=$azureAdJoined; DomainJoined=$domainJoined; Domain=$domainName" 'Entra-based AVD SSO may not work as expected without Entra/hybrid join.' 'Review join design; use hybrid or Entra join aligned with AVD SSO requirements.' 'Identity and join state') }
        default { Add-Finding (New-Finding 'JOIN-UNKNOWN' 'High' 'Session host join state is unknown or inconsistent' "AzureAdJoined=$azureAdJoined; DomainJoined=$domainJoined; EnterpriseJoined=$enterpriseJoined; WorkplaceJoined=$workplaceJoined" 'Inconsistent join state commonly causes SSO failures.' 'Repair device registration/join state before tuning RDP flags.' 'Identity and join state') }
    }
    if($azureAdJoined -eq 'YES'){ foreach($field in @('DeviceAuthStatus','AzureAdPrt','NgcSet')){ if($ds.Contains($field) -and $ds[$field] -match 'NO|FAILED|ERROR'){ Add-Finding (New-Finding "DSREG-$field" 'Medium' "dsregcmd reports $field is not healthy" "$field=$($ds[$field])" 'Token or device auth issues can break seamless sign-in.' 'Inspect AAD/Operational events and re-register device if needed.' 'Identity and join state') } } }
    $services=foreach($name in 'RDAgentBootLoader','RDAgent','TermService'){ Get-Service -Name $name -ErrorAction SilentlyContinue | Select-Object Name,Status,StartType }; $evidence.Checks.Services=@($services)
    foreach($svcName in 'RDAgentBootLoader','RDAgent'){ $svc=$services | Where-Object Name -eq $svcName; if(-not $svc){ Add-Finding (New-Finding "SVC-$svcName-MISSING" 'High' "$svcName service not found" 'Service query returned no result.' 'AVD host may not be correctly registered/agent installed.' 'Repair/reinstall AVD agent and bootloader.' 'Session host VM state') } elseif($svc.Status -ne 'Running'){ Add-Finding (New-Finding "SVC-$svcName-NOTRUNNING" 'High' "$svcName is not running" "Status=$($svc.Status); StartType=$($svc.StartType)" 'AVD control plane connectivity and sign-in may fail.' 'Start/repair the service and check agent event logs.' 'Session host VM state') } }
    $evidence.Checks.Registry=[ordered]@{ CredSSPPolicy=Get-RegValueSafe 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters' 'AllowEncryptionOracle'; TerminalServerDenyTSConnections=Get-RegValueSafe 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' 'fDenyTSConnections'; WHfBEnabled=Get-RegValueSafe 'HKLM:\SOFTWARE\Policies\Microsoft\PassportForWork' 'Enabled'; CloudKerberosTicketRetrievalEnabled=Get-RegValueSafe 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' 'CloudKerberosTicketRetrievalEnabled' }
    if($evidence.Checks.Registry.TerminalServerDenyTSConnections -eq 1){ Add-Finding (New-Finding 'RDP-DISABLED-REGISTRY' 'High' 'Remote Desktop connections appear disabled in registry' 'fDenyTSConnections=1.' 'Users may not be able to connect or validate SSO.' 'Confirm RDP enablement and AVD agent policy.' 'Session host VM state') }
    $logs=[ordered]@{}; foreach($log in @('Microsoft-Windows-AAD/Operational','Microsoft-Windows-TerminalServices-LocalSessionManager/Operational','Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational','Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational','Application','System')){ $logs[$log]=@(Get-RecentEventsSafe $log 15) }; $evidence.Checks.RecentEvents=$logs
    foreach($logName in $logs.Keys){ $bad=@($logs[$logName] | Where-Object { $_.LevelDisplayName -match 'Error|Critical' }); if($bad.Count -gt 0){ Add-Finding (New-Finding ('LOG-' + ($logName -replace '[^A-Za-z0-9]','-')) 'Medium' "Recent errors in $logName" "$($bad.Count) recent error/critical events found." 'Recent authentication or RDP errors may identify the failing stage.' 'Review the JSON event samples and correlate with affected login time.' 'Logs and event evidence') } }
    $endpoints=@('login.microsoftonline.com','device.login.microsoftonline.com','rdweb.wvd.microsoft.com','rdbroker.wvd.microsoft.com'); if($AdditionalDomainControllers.Count -gt 0){$endpoints += $AdditionalDomainControllers}; $net=@(); foreach($ep in $endpoints){$net += Test-Tcp $ep 443}; foreach($dc in $AdditionalDomainControllers){$net += Test-Tcp $dc 88; $net += Test-Tcp $dc 389}; $evidence.Checks.Network=$net; foreach($n in $net | Where-Object { -not $_.Reachable }){ Add-Finding (New-Finding 'NET-ENDPOINT-UNREACHABLE' 'Medium' "Endpoint unreachable: $($n.Host):$($n.Port)" 'TCP test failed.' 'Network, DNS, proxy, or firewall blocks can prevent token/AVD/Kerberos flows.' 'Validate DNS/proxy/firewall rules for this endpoint.' 'Networking, DNS, proxy, outbound, or private access') }
} catch { Add-Finding (New-Finding 'SCRIPT-ERROR' 'Critical' 'Session-host diagnostic failed before completion' (Redact-Text $_.Exception.Message) 'The report may be incomplete.' 'Resolve the error and rerun.' 'Script runtime') }
$severityRank=@{ Critical=5; High=4; Medium=3; Low=2; Info=1 }; $actionable=@($Findings | Where-Object Severity -ne 'Info' | Sort-Object { -$severityRank[$_.Severity] })
$overall=if($actionable | Where-Object Severity -in @('Critical','High')){'Likely Misconfigured'}elseif($actionable | Where-Object Severity -eq 'Medium'){'Partially Configured'}elseif($actionable.Count -gt 0){'Needs Manual Review'}else{'Healthy'}; $top=if($actionable.Count){$actionable[0].Title}else{'No blocking VM-side SSO issue detected by this script.'}
$report=[ordered]@{ OverallStatus=$overall; DetectedScenario=$scenario; TopLikelyCause=$top; Findings=@($Findings); Evidence=$evidence }; $report | ConvertTo-Json -Depth 12 | Set-Content -Path $OutputPath -Encoding UTF8
Write-Host "AVD SSO Session Host Diagnostic: $overall" -ForegroundColor Cyan; Write-Host "Detected scenario: $scenario"; Write-Host "Top likely cause: $top"; Write-Host "Report: $OutputPath"; $Findings | Sort-Object { -$severityRank[$_.Severity] } | Format-Table Severity,Title,Domain -AutoSize
if($Markdown){ $mdPath=[IO.Path]::ChangeExtension($OutputPath,'.md'); $md=@('# AVD SSO Session Host Diagnostic','',"- Overall status: **$overall**","- Detected scenario: $scenario","- Top likely cause: $top",'','## Findings'); foreach($f in ($Findings | Sort-Object { -$severityRank[$_.Severity] })){ $md += "### [$($f.Severity)] $($f.Title)`n- Domain: $($f.Domain)`n- Evidence: $($f.Evidence)`n- Impact: $($f.Impact)`n- Recommendation: $($f.Recommendation)`n" }; $md | Set-Content -Path $mdPath -Encoding UTF8; Write-Host "Markdown: $mdPath" }
